const raw =
  $json.content?.parts?.[0]?.text ??
  $json.output ??
  $json.text ??
  $json.response ??
  '';

if (!raw) {
  throw new Error('No Gemini text output found.');
}

let text = typeof raw === 'string'
  ? raw
  : String(raw);

// Remove markdown/code fences
text = text
  .replace(/```(?:html|markdown|text)?/gi, '')
  .replace(/```/g, '')
  .trim();

// Extract subject
const subjectMatch = text.match(/^Subject:\s*(.+)$/im);

const subject = subjectMatch
  ? subjectMatch[1].trim()
  : 'Application – Computer Engineer | Data, BI & AI';

// Remove subject
let body = text
  .replace(/^Subject:\s*.+$/im, '')
  .trim();

// Remove accidental "Email body:"
body = body
  .replace(/^Email body:\s*/i, '')
  .trim();

// Remove any Resume markdown/link generated by Gemini
body = body.replace(
  /\[Resume\]\s*\\?\(\s*https?:\/\/[^)]+\s*\\?\)/gi,
  'Resume'
);

// Also remove a raw Resume URL if Gemini added one
body = body.replace(
  /https?:\/\/drive\.google\.com\/[^\s)]+/gi,
  'Resume'
);

// Escape HTML special characters
function escapeHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

body = escapeHtml(body);

// Convert paragraphs separated by blank lines
let htmlBody = body
  .split(/\n\s*\n/)
  .map(paragraph => `<p>${paragraph.replace(/\n/g, '<br>')}</p>`)
  .join('\n');

// Insert real Resume link
const resumeUrl =
  'https://drive.google.com/file/d/1dLoSv08wOb7yQaAbKdTWzLPb9Wc2u14d/view?usp=sharing';

htmlBody = htmlBody.replace(
  /Resume/g,
  `<a href="${resumeUrl}">Resume</a>`
);

// Get recipient
const to =
  $('Clean Data').item.json.email ??
  $json.email ??
  '';

if (!to) {
  throw new Error('Recipient email not found.');
}

return {
  json: {
    to: String(to),
    subject: String(subject),
    emailBody: htmlBody,
    candidateName: 'HADIL DEROUICH',
    resumeName: 'Resume',
    resumeLink: resumeUrl,
    parsedSuccessfully: true
  }
};